# Generated by Django 2.2.24 on 2021-07-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=135, verbose_name='姓名')),
                ('city', models.CharField(max_length=135, verbose_name='城市')),
                ('phone', models.CharField(max_length=135, verbose_name='手机号码')),
                ('email', models.EmailField(blank=True, max_length=135, verbose_name='邮箱')),
                ('apply_position', models.CharField(blank=True, max_length=135, verbose_name='应聘职位')),
                ('born_address', models.CharField(blank=True, max_length=135, verbose_name='生源地')),
                ('gender', models.CharField(blank=True, max_length=135, verbose_name='性别')),
                ('candidate_remark', models.CharField(blank=True, max_length=135, verbose_name='候选人信息备注')),
                ('creator', models.CharField(blank=True, max_length=256, verbose_name='候选人数据的创建人')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('last_editor', models.CharField(blank=True, max_length=256, verbose_name='最后编辑者')),
            ],
            options={
                'verbose_name': '应聘者',
                'verbose_name_plural': '应聘者',
                'db_table': 'canditate',
            },
        ),
    ]
