# Generated by Django 2.2.24 on 2021-07-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'permissions': [('export', 'Can export db'), ('notify', 'Can notify message')], 'verbose_name': '应聘者', 'verbose_name_plural': '应聘者'},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='born_address',
            field=models.CharField(blank=True, help_text='老家是哪里的呀？', max_length=135, verbose_name='生源地'),
        ),
    ]
